name: Tests

on:
  workflow_dispatch:
  push:
  merge_group:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9, "3.10", "3.11"]
    uses: qiboteam/workflows/.github/workflows/rules-poetry.yml@v1
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      doctests: false
      poetry-extras: --all-extras
    secrets: inherit
